spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST:192.168.40.168}
    port: ${RABBIT_MQ_PORT:5600}
    username: feng
    password: feng
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/ag_zipkin?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: feng
    driver-class-name: com.mysql.jdbc.Driver
    initialize: true
    continue-on-error: true
  application:
    name: ace-trace
   #zipkin数据保存到数据库中需要进行如下配置
   #表示当前程序不使用sleuth
  sleuth:
    enabled: false
   #表示zipkin数据存储方式是mysql
zipkin:
  storage: typemysql

server:
  port: 9411

eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        # docker 部署开启
#        prefer-ip-address: true
#        ip-address: 127.0.0.1
    client:
        serviceUrl:
#            defaultZone: http://localhost:8761/eureka/
                    # docker 部署开启
            defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
